inherit_from:
  - .rubocop_todo.yml

require:
  - rubocop-rspec

AllCops:
  DefaultFormatter: fuubar
  EnabledByDefault: true
  TargetRubyVersion: 2.3
  Exclude:
    - 'vendor/bundle/**/*'
    - '**/*\.spec'
