#ifndef EXTCONF_H
#define EXTCONF_H
#define HAVE_MAGICK_MAGICKCORE_H 1
#define HAVE_GETIMAGECHANNELENTROPY 1
#define HAVE_SETIMAGEGRAY 1
#define RUBY_VERSION_STRING ruby 2.6.3
#define RMAGICK_VERSION_STRING RMagick 4.0.0
#define IMAGEMAGICK_GREATER_THAN_EQUAL_6_8_9 1
#define IMAGEMAGICK_GREATER_THAN_EQUAL_6_9_0 1
#endif
